server:
  servlet:
    context-path: /api


spring:
  datasource:
    password: ENC(UENUlWqBNf2EwH9wY4AUbIuOfFj8g1fE)
    username: ENC(nNpYuEyJwrtcc1wH9d1+cg==)
    url: ENC(GWkhJ1en1NhxsoQebNW1ZpyBRPNi/8/TxK0BWolj87MnPpPuORVBc4n9++XD4adt)


  jpa:
    hibernate:
      ddl-auto: none # 외래키 설정 없이 직접 테이블을 생성하기 위해서

    properties:
      hibernate:
        show_sql: true
        format_sql: true

    open-in-view: false # 성능 측면에서 false로 설정

# JWT Configuration
jwt:
  secret-key: ENC(9hJ5k3L8m2N4p7Q1r6T9v5X8z3C6f2G9h5K8l3M6n9P2q7R4t9V5x8Z1c6F9g3H6)
  access-token-validity: 3600000  # 1 hour in milliseconds
  refresh-token-validity: 604800000  # 7 days in milliseconds

# External API Configuration
external-api:
  fin-open-api:
    base-url: https://finopenapi.ssafy.io/ssafy/api/v1
    manager-id: ssafy@ssafy.co.kr